### ISSUE TITLE
스쿼트 모션 관련 : 카운팅하기

### ISSUE THREAD

**Issue by WOODBRICKS** [ProjectInTheClass/squat#2]
스쿼트 모션을 머신러닝으로 구현하기

**Comment by WOODBRICKS** [comment]
### 기술적 이슈 #1차 

- 스쿼트를 측정하는 기술을 찾아보고, 공부해야함
- 애플워치 측정은 사용자 타겟팅이 좁게 한정되므로 배제
- 전면 / 후면 각각의 카메라로 모션을 감지하는 딥러닝을 공부할 필요가 있음

**Comment by melobron** [comment]
coreML image Classification 통해 3가지 운동 분류 학습
